export const config = {
  hasktagsPath: {
    type: 'string',
    default: 'hasktags.js',
    description: `Path to hasktags executable; if set to 'hasktags.js'
(default) will use bundled ghcjs-powered implementation`,
  },
  ignoreCloseImplementation: {
    type: 'boolean',
    default: 'false',
    description: `Ignore symbols with the same name that are close together
in terms of lines. May require restart.`,
  },
  ignoreVCSIgnoredPaths: {
    type: 'boolean',
    default: 'true',
    description: 'Ignore paths in `.gitignore` (if any).',
  },
}

// generated by typed-config.js
declare module 'atom' {
  interface ConfigValues {
    'ide-haskell-hasktags.hasktagsPath': string
    'ide-haskell-hasktags.ignoreCloseImplementation': boolean
    'ide-haskell-hasktags.ignoreVCSIgnoredPaths': boolean
    'ide-haskell-hasktags': {
      hasktagsPath: string
      ignoreCloseImplementation: boolean
      ignoreVCSIgnoredPaths: boolean
    }
  }
}
